export enum ProductCategory {
  ELECTRONICS = 'ELECTRONICS',
  FASHION = 'FASHION',
  HOUSE_GARDEN = 'HOUSE_GARDEN',
  BABY = 'BABY',
  BEAUTY = 'BEAUTY',
  HEALTH = 'HEALTH',
  ENTERTAINMENT = 'ENTERTAINMENT',
  SPORT = 'SPORT',
  SERVICES = 'SERVICES',

}
